### ISSUE TITLE
博客图片无法正常显示

### ISSUE THREAD

**Issue by th31nk** [dunwu/javacore#16]
兄弟。。你基础语法特性那一篇的图片好像都无法正常显示了。。但是如果f12直接进去找链接还是可以看到的

**Comment by dunwu** [comment]
可以显示的，应该是加载超时，浏览器就不显示了

**Comment by bmxklYzj** [comment]
https://gitee.com/turnon/javacore/blob/master/docs/basics/java-basic-grammar.md

![image](https://user-images.githubusercontent.com/14893159/106781412-fe696100-6683-11eb-9fcd-c41735e7e463.png)

我的也是，图片全都访问不了，拷贝图片连接到新tab可以访问，求修复

**Comment by bmxklYzj** [comment]
额，刚换了safari浏览器可以，chrome不行。。
