### ISSUE TITLE
楼主，希望修复一下网站的图片链接

### ISSUE THREAD

**Issue by jhyscode** [dunwu/javacore#18]
https://dunwu.github.io/，
此网站的文章大部分引用的图片应该是失效了，希望大佬更新一下。

**Comment by dunwu** [comment]
好的，最近有点忙，我会抽时间逐一修复，抱歉

**Comment by dunwu** [comment]
> [https://dunwu.github.io/，](https://dunwu.github.io/%EF%BC%8C)
> 此网站的文章大部分引用的图片应该是失效了，希望大佬更新一下。

基本上已经修复了
