### ISSUE TITLE
顶层目录无法跳转

### ISSUE THREAD

**Issue by ccsugar** [dunwu/javacore#33]
https://dunwu.github.io/javacore/basics/java-annotation.html
顶层目录无法跳转

**Comment by TremblingFool** [comment]
[1. 注释](#1-注释) 应该换成 [1. 注释](#1注释)； 标题中如果存在"."，在目录中不体现

**Comment by dunwu** [comment]
1. md 目录是在 Visual stuido 中通过插件自动生成的
2. 生成的目录在 md 编辑器或 Github 页面中是可以正常跳转的，只是在 vuepress 生成的电子书页面中不起作用
——综上，目前不做修改
