### ISSUE TITLE
图片文字错误

### ISSUE THREAD

**Issue by TremblingFool** [dunwu/javacore#34]
![image](https://user-images.githubusercontent.com/64069911/150708990-6adbdf9d-29f4-4278-9dc9-cfec33b9b4fa.png)
在Java基础语法特性的“7.方法”的图片中，Java写成了ava

**Comment by dunwu** [comment]
> ![image](https://user-images.githubusercontent.com/64069911/150708990-6adbdf9d-29f4-4278-9dc9-cfec33b9b4fa.png) 在Java基础语法特性的“7.方法”的图片中，Java写成了ava

@TremblingFool 谢谢指正，已修复
