### ISSUE TITLE
ArrayList的clone是浅拷贝

### ISSUE THREAD

**Issue by 710409407** [dunwu/javacore#37]
https://github.com/dunwu/javacore/blob/master/docs/03.%E5%AE%B9%E5%99%A8/02.Java%E5%AE%B9%E5%99%A8%E4%B9%8BList.md#arraylist

**Comment by dunwu** [comment]
文中说的不就是浅拷贝吗

**Comment by 710409407** [comment]
图片里啊

**Comment by 710409407** [comment]
图片里啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月23日(星期一) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dunwu/javacore] ArrayList的clone是浅拷贝 (Issue #37)






文中说的不就是浅拷贝吗

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by dunwu** [comment]
@710409407 已修改，谢谢指正
